---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/projects
  label: Portfolio
  create: documents
  match: "**/*"
  templates:
  - portfolio-item
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - blog-post
upload_dir: content/images
public_path: "/static/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
